# Generated by Django 4.0.6 on 2022-08-01 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=2000)),
                ('message', models.TextField(default='', max_length=2000)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('fcm_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcm_app.fcmapp')),
            ],
        ),
    ]
