# Generated by Django 4.0.6 on 2022-08-02 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_app', '0003_device_user_name_alter_device_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='additional_message',
            field=models.TextField(default='', max_length=3000),
        ),
    ]
