# Generated by Django 4.0.6 on 2022-08-02 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_app', '0004_notification_additional_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.CharField(default='', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='image_url',
            field=models.CharField(default='', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='link_url',
            field=models.CharField(default='', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='additional_message',
            field=models.TextField(default='', max_length=3000, null=True),
        ),
    ]
